name: workflow1
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: task1
        id: taskid1
        run: echo "hello" 
      - name: task2
        if: failure() && steps.taskid1.outcome == 'failure' || success() && steps.taskid1.outcome == 'success'
        run: echo "run only if task1 fails or success"
